### ISSUE TITLE
Add flags for seamlessClone

### ISSUE THREAD

**Issue by omi-n** [rquit/landmarks_face_swap#3]
Add flags to toggle the seamlessClone mode (cv2.NORMAL_CLONE, cv2.MIXED_CLONE, and an option to turn it off).

**Comment by rquit** [comment]
[56ba0d1](https://github.com/rquit/landmarks_face_swap/commit/56ba0d10cbcbc9c090cb4d62aba8683844a2331c)

**Comment by omi-n** [comment]
[c32f398](https://github.com/rquit/landmarks_face_swap/commit/c32f398a8be28a813f6dde6a2a984f7e05fd20eb)
